### ISSUE TITLE
Netlify deploy

### ISSUE THREAD

**Issue by Sumo99** [NickFoden/mascota#12]
https://mascota.netlify.com/ is missing the new favicon of the dog paw. I have noticed that it looks different from my local project as well.

**Comment by NickFoden** [comment]
I think it is working now. Is this correct ?

![image](https://user-images.githubusercontent.com/8321838/55689927-e118be00-5958-11e9-948e-6dee14743d48.png)

**Comment by Sumo99** [comment]
Yup, I see that you have made changes.
