### ISSUE TITLE
How to build

### ISSUE THREAD

**Issue by Sumo99** [NickFoden/mascota#9]
I have tried npm install and npm start, but I get a blank index and home page.

**Comment by Sumo99** [comment]
Probably a stupid question

**Comment by NickFoden** [comment]
Hi sumo99 you will need a .env file in the roof of your directory with the firebase database keys.

**Comment by Sumo99** [comment]
I got it working. is this what you see when you login 

{"error":{"code":400,"message":"API key not valid. Please pass a valid API key.","errors":[{"message":"API key not valid. Please pass a valid API key.","domain":"global","reason":"badRequest"}],"status":"INVALID_ARGUMENT"}}

?

**Comment by NickFoden** [comment]
Either you can email me and I can send you the api keys for our sandbox, or you can run on your own firebase db, where you will need to initialize the app and then with either db you will need the following to be in a env file and with valid values in each of the " "  

`.env` file 


```javascript
  REACT_APP_API_KEY=" "
  REACT_APP_AUTH_DOMAIN=" "
  REACT_APP_DATABASE_URL=" "
  REACT_APP_PROJECT_ID=" "
  REACT_APP_STORAGE_BUCKET=" "
  REACT_APP_MESSAGING_SENDER_ID=" "
```

**Comment by Sumo99** [comment]
No I got my own db. I have my api key as well.

**Comment by NickFoden** [comment]
you may need to restart the repo, also this is a work in progress, so the actual log in and out is not finalized yet.
